In [1]:
# %load_ext autoreload
# %autoreload 2
from class_new import *
from class_new import *
import class_new
import importlib
importlib.reload(class_new)

ModuleNotFoundError: No module named 'class_new'

In [6]:
# import import_ipynb

import sys
sys.path.append('C:/Users/GJ/PycharmProjects/2022SPCUP')


from class_new import *
import class_new
import importlib
importlib.reload(class_new)

import tensorflow as tf
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, recall_score, accuracy_score, precision_score

from tensorflow.keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout, UpSampling2D, Input, Convolution2D, Reshape

known_volume_path = './part2_full_train_4X5000'
unknown_volume_path = './unseen_noisy_4X1000'




rs = 10
known_path, known_labels = part2_file_path_list(known_volume_path,label = True)
unknown_path, unknown_labels = part2_file_path_list(unknown_volume_path,label = False)

# print(known_path)
print(known_labels.shape)
print(unknown_labels.shape)

all_path = np.concatenate((known_path,unknown_path),axis = 0)
all_labels = np.concatenate((known_labels,unknown_labels),axis = 0)
print(all_labels.shape)


##train set
# print('raw train_set_num :',len(labels))
X_train_path, X_test_path, y_train_raw, y_test_raw = train_test_split(all_path,
                                                                      all_labels, test_size=0.2,
                                                                      stratify = all_labels, random_state=rs)


n_mels = 64
samplint_rate = 16000
# train = classes.data(X_train_path, y_train_raw, n_mels=n_mels, known = True)
# # X_train,y_train = train.extract_mel(sampling_rate,n_mels)

# test = classes.data(X_test_path, y_test_raw, n_mels=n_mels, known = True)
# # X_test,y_test = test.extract_mel(sampling_rate,n_mels)

# unseen = data(unknown_path, unknown_labels, n_mels=n_mels, known = False)

# n = -1

train = data(X_train_path,y_train_raw,n_mels=n_mels, known = True)

test = data(X_test_path,y_test_raw, n_mels=n_mels, known = True)

train.extract_mel()
test.extract_mel()

train.reshape_data()
test.reshape_data()


# import pickle
# with open('part2_train_rs10_nmels64(train5000x4+unseen1000x4).p','wb') as f:
#     pickle.dump(train,f)
    
# with open('part2_test_rs10_nmels64(train5000x5+unseen1000x4).p','wb') as f:
#     pickle.dump(test,f)
    

ModuleNotFoundError: No module named 'matplotlib.pyplot'

In [26]:
# # print(train_data.X_split.shape)
# np.save('part2_cnn_train_data_train(train24000(19200))',train.X_reshaped)
# np.save('part2_cnn_train_data_test(train24000(4800))',test.X_reshaped)
# np.save('part2_cnn_train_data_train(train24000(19200))_file_split_num',train.file_split_num)
# np.save('part2_cnn_train_data_test(train24000(4800))_file_split_num',test.file_split_num)

In [19]:
print(test_soft.shape)
print(y_test_raw)

test_data = pd.DataFrame(test_soft)
y_test_data = pd.DataFrame(y_test_raw)



sort_test = np.concatenate((test_soft[y_test_raw == 0],test_soft[y_test_raw == 1],test_soft[y_test_raw == 2],
                          test_soft[y_test_raw == 3],test_soft[y_test_raw == 4],test_soft[y_test_raw == 5]),axis = 0)

sort_y = np.concatenate((y_test_raw[y_test_raw == 0],y_test_raw[y_test_raw == 1],y_test_raw[y_test_raw == 2],
                          y_test_raw[y_test_raw == 3],y_test_raw[y_test_raw == 4],y_test_raw[y_test_raw == 5]),axis = 0)
                         
test_data = pd.DataFrame(sort_test)
y_test_data = pd.DataFrame(sort_y)
                        
dataframe = pd.concat([test_data,y_test_data],axis =1)
dataframe.head()
# sort_test = np.concatenate((test_soft[test.y_split == 0],mse_test[test.y_split == 1],mse_test[test.y_split == 2],
#                           mse_test[test.y_split == 3],mse_test[test.y_split == 4],mse_unseen),axis = 0)

import pandas as pd




dataframe.to_csv('part2_sort_test4800_before_softmax.csv')


print(test_soft.shape)

(4800, 6)
[3 0 3 ... 2 3 2]


0         1        2          3        4        5  0
0  27.923611 -10.24041  3.37297 -14.518420 -0.03298  1.61664  0
1  33.389210 -10.11042  2.07186 -13.771770  0.47234  0.90537  0
2  20.265310  -5.81627  3.24517 -13.077560  2.87962 -2.03864  0
3  36.896870 -14.44131  4.90045 -14.386620 -3.87557  3.93026  0
4  35.944290 -12.05013  1.43356 -17.065741 -3.28322  3.10575  0

(4800, 6)


In [30]:
print(train.X_reshaped.shape)
print(test.X_reshaped.shape)

(124002, 64, 32, 1)
(30844, 64, 32, 1)


In [7]:
import pickle
with open('part2_train_rs10_nmels128(train5000x4+unseen1000x4).p','wb') as f:
    pickle.dump(train,f)
with open('part2_testrs10_rs10_nmels128(train5000x5+unseen1000x4).p','wb') as f:
    pickle.dump(test,f)



# with open("part1_label6_train.p", 'rb') as f:
#     train = pickle.load(f)
# with open("part1_label6_test.p", 'rb') as f:
#     test = pickle.load(f) 

PicklingError: Can't pickle <class 'class_new.data'>: it's not the same object as class_new.data

In [ ]:
# X_train = train.X_reshaped
# X_test = test.X_reshaped
# y_train = train.y_reshaped
# y_test = test.y_reshaped
# print(y_train.shape)

In [5]:

X_train = train.X_reshaped
X_test = test.X_reshaped
y_train = train.y_reshaped
y_test = test.y_reshaped

for n_mels in [128]:
    for hop_length in [512]:
        for n_fft in [2048]:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Flatten, Conv2D, MaxPool2D
            from tensorflow.keras.callbacks import EarlyStopping
            from tensorflow.keras.callbacks import ModelCheckpoint

            print((X_train.shape[1:]))
            model = Sequential()

            #model 2
            model.add(layers.BatchNormalization(input_shape=(X_train.shape[1:])))
            model.add(layers.Conv2D(filters=16, kernel_size=(5, 5), padding="same", activation='relu'))
            model.add(layers.BatchNormalization())
            model.add(layers.Conv2D(filters=32, kernel_size=(5, 5), padding="same", activation='relu'))
            model.add(layers.BatchNormalization())
            model.add(layers.Conv2D(filters=64, kernel_size=(5, 5), padding="same", activation='relu'))
            model.add(MaxPool2D(pool_size=(5, 5)))
            model.add(Flatten())
            model.add(layers.Dense(6, activation=None))
            model.add(layers.Activation('softmax'))


            # 모델 컴파일
            model.compile(optimizer='adam',
                          loss='categorical_crossentropy',
                          metrics=['accuracy'])


            callbacks = [EarlyStopping(monitor='val_loss', min_delta=0, patience=100, mode='auto',restore_best_weights=True), 
                         ModelCheckpoint(filepath=str(n_mels)+"_"+str(hop_length)+"_"+ str(rs) + "_"
                                         + "part2_mel_feature128_label_6_model.h5",
                                         monitor='val_loss', verbose=0, save_best_only=True)]

            classifier = model.fit(X_train,
                                   y_train,
                                   epochs=1000,
                                   batch_size=128, callbacks=callbacks,
                                   validation_split=0.2)

#             model_json = model.to_json()
#             with open("./models_log" + "/" + str(rs) + "_" + "spcup.json", 'w') as json_file:
#                 json_file.write(model_json)
            #             model.save_weights("./models_log" + "/" + str(rs) + "_" + "spcup.h5")
            print("Saved model to disk")


            #             #### json 모델 load
            #             from keras.models import model_from_json
            #             json_file = open("model.json", "r") 
            #             loaded_model_json = json_file.read() 
            #             json_file.close() 
            #             loaded_model = model_from_json(loaded_model_json)

            plt.plot(classifier.history['accuracy'])
            plt.plot(classifier.history['val_accuracy'])
            # plt.plot(classifier.history['loss'])
            # plt.plot(classifier.history['val_loss'])
            plt.legend([ 'accuracy','val_accuracy'], loc = 'upper left')
            plt.show()

            test_loss, test_acc = model.evaluate(X_test,  y_test, verbose=2)

            print('테스트 정확도:', test_acc)

            prediction = model.predict(X_test)




            #######################segment들 합쳐서 파일당 accuracy 계산
            from scipy.stats import mode
            predicted_classes = np.argmax(prediction, axis = 1)
            f = 0
            test_predict=[]
            for i in file_split_num:
            #     print(predicted_classes[f:f+i])
                test_predict.append(mode(predicted_classes[f:f+i])[0][0])
                f+=i

            acc_bool = test_predict==y_test_raw
            #             print(test_predict[:100])
            #             print(y_test_raw[:100])
            #             print(acc_bool[:100])
            test_accuracy = acc_bool.tolist().count(True)/len(acc_bool)
            print('************ mel_spectogram')
            print('************ file test_accuracy : ', test_accuracy, '  n_mels : ', n_mels,
                  ', hop_length = ', hop_length,' , n_fft : ',n_fft)
            print('************ X_train.shape : ', X_train.shape)
            print('test_set.size : ', acc_bool.size)
            print('\n\n\n')

            df.append({'n_mels':n_mels,'hop_length':hop_length,'n_fft':n_fft,'rs':rs,'accuracy':test_accuracy,'input_shape':X_train.shape},ignore_index = True)
            df.to_csv("models_log.csv",sep=",")




(64, 32, 1)
Epoch 1/1000
776/776 [==============================] - 118s 148ms/step - loss: 0.8871 - accuracy: 0.6918 - val_loss: 0.4837 - val_accuracy: 0.8187
Epoch 2/1000
680/776 [=========================>....] - ETA: 13s - loss: 0.3067 - accuracy: 0.8783

KeyboardInterrupt: 

In [ ]:
model.save("./best_model_noise" + "/" + str(rs) + "_" + "part2_label6_spcup_save_last.h5")

In [31]:
from sklearn.metrics import confusion_matrix
cf = confusion_matrix(y_test_raw, test_predict)
print('\n\n', cf)



 [[800   0   0   0   0   0]
 [  0 797   3   0   0   0]
 [  0  15 781   0   0   4]
 [  0   0   0 800   0   0]
 [  0   0   0   0 800   0]
 [  0   0   0   0   0 800]]


In [50]:
num = 0
idx_p = []
for idx, i in enumerate(X_test_path):
    if ("noise"  not in i) and ("reverb" not in i) and ("compressed" not in i):
        idx_p.append(idx)
        num+=1
print(num)

1238


In [54]:
model = load_model('./best_model_noise/10_part2_label6_spcup_save_last.h5')

In [53]:
X_test_path[idx_p]
y_test_raw[idx_p]

from sklearn.metrics import confusion_matrix
cf = confusion_matrix(y_test_raw[idx_p], test_predict[idx_p])
print('\n\n', cf)



 [[216   0   0   0   0   0]
 [  0 187   0   0   0   0]
 [  0   0 215   0   0   0]
 [  0   0   0 208   0   0]
 [  0   0   0   0 220   0]
 [  0   0   0   0   0 192]]


In [ ]:
from tensorflow.keras.models import load_model

# model = load_model('./64_1024_10_part2_mel_feature_label_6_model.h5')
model = load_model('./best_model_noise/10_part2_label6_spcup_save_last.h5')

# model_vec = load_model('./64_1024_10_part2_mel_feature_label_6_model.h5')
model_vec = load_model('./best_model_noise/10_part2_label6_spcup_save_last.h5')

model_vec.pop()
model_vec.compile()
model_vec.summary()

def ext_soft(data, model, model_vec, n_round = 5):
    

    
    prediction_soft = model.predict(data.X_reshaped)
    prediction_vec = model_vec.predict(data.X_reshaped)
    predicted_classes = np.argmax(prediction_soft, axis=1)
    

    
    f = 0
    softmax_val = []
    test_predict = []

    for j,i in enumerate(data.file_split_num):
        mean_vec = np.mean(prediction_vec[f:f + i],axis = 0)    
        mean_soft = np.mean(prediction_soft[f:f + i],axis = 0) 
#         mean_soft = np.mean(prediction[f:f + i],axis = 0)
#         mean_soft = np.mean(np.power(prediction[f:f + i],2),axis = 0)
        
        softmax_val.append(np.round(mean_vec,n_round))
#         test_predict.append(mode(predicted_classes[f:f + i])[0][0])
        test_predict.append(np.argmax(mean_soft))
        
#         predicted_classes = np.argmax(np.mean(np.power(prediction[f:f + i],1),axis = 0))
#         test_predict.append(predicted_classes)
        f += i
    return np.array(softmax_val), np.array(test_predict)

soft_val, test_predict = ext_soft(test,model,model_vec, 5)



In [ ]:
y_test_raw[:-1].shape

In [ ]:
from sklearn.metrics import confusion_matrix
cf = confusion_matrix(np.array(y_test_raw)[:-1], test_predict)
print('\n\n', cf)

In [ ]:
 #######################segment들 합쳐서 파일당 accuracy 계산
from scipy.stats import mode
predicted_classes = np.argmax(prediction, axis = 1)
f = 0
test_predict=[]
for i in test.file_split_num:
#     print(predicted_classes[f:f+i])
    test_predict.append(mode(predicted_classes[f:f+i])[0][0])
#     print(test_predict)
    f+=i

test_predict = np.array(test_predict)
print(len(test.file_split_num))
print(test_predict.shape)
print(y_test_raw.shape)


acc_bool = test_predict==y_test_raw[:-1]
print(acc_bool)
#             print(test_predict[:100])
#             print(y_test_raw[:100])
#             print(acc_bool[:100])
test_accuracy = acc_bool.tolist().count(True)/len(acc_bool)
print('************ mel_spectogram')
print('************ file test_accuracy : ', test_accuracy, '  n_mels : ', n_mels,
      ', hop_length = ', hop_length,' , n_fft : ',n_fft)
print('************ X_train.shape : ', X_train.shape)
print('test_set.size : ', acc_bool.size)
print('\n\n\n')
print('saved_mdel_name : ', "./models_log" + "/" +str(n_mels)+"_"+str(hop_length)+"_"+ str(rs) + "_"
                                         + "othre_feature_label_6_model.h5" )
# df.append({'n_mels':n_mels,'hop_length':hop_length,'n_fft':n_fft,'rs':rs,'accuracy':test_accuracy,'input_shape':X_train.shape},ignore_index = True)
# df.to_csv("models_log.csv",sep=",")

from sklearn.metrics import confusion_matrix
cf = confusion_matrix(y_test_raw[:-1], test_predict)
print('\n\n', cf)